config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get "/browse", to: "loan_requests#index"

  get "/portfolio", to: "borrower_portfolio#show"

  resources :payment, only: [:update]

  resources :loan_requests

  get "/cart", to: "cart#index"
  post "/cart", to: "cart#create"
  delete "/cart", to: "cart#delete"
  put "/cart", to: "cart#update"

  resources :orders, only: [:create, :index, :show, :update]

  get "/login", to: "sessions#new", :as => "login"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  delete "/logout", to: "sessions#destroy"

  resources :lenders

  resources :borrowers

  resources :users, only: [:show]

  get "*path", to: "home#not_found"
end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
  before_action :set_borrower, only: [:show]

  def new
    @user = User.new
  end

  def create
    user = User.new(borrower_params.merge(role: "borrower"))
    if user.save
      session[:user_id] = user.id
      flash[:notice] = "You've been saved"
      redirect_to borrower_path(user)
    else
      flash[:error] = "Something went wrong. Please try again"
      render partial: "borrowers/new"
    end
  end

  def show
    @loan_requests = LoanRequest.where(user_id: params[:id])
  end

  private

  def borrower_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_borrower
    @borrower = User.find(params[:id])
  end

  def this_borrower?
    current_user && current_user.borrower? && current_user.id == params[:id].to_i
  end

  helper_method :this_borrower?
end

app/views/borrowers/_borrower_show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 pull-left">
      <a href="#" class="btn btn-info" role="button" data-toggle="modal" data-target="#loanRequestModal">Create Loan Request</a>
    </div>

    <%= render "shared/search" %>

  </div>
</div>

<br>

<%= render "shared/borrower_thumbnail" %>

<!-- Create Loan Request Modal -->
<div class="modal fade" id="loanRequestModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= render "new_loan_request" %>
    </div>
  </div>
</div>

<div id="loan-request-modal" class="modal fade"></div>

app/views/borrowers/_lender_show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 pull-left">
      <select class="form-control btn-info">
        <option value="farming">Farming</option>
        <option value="education">Education</option>
        <option value="medical">Medical</option>
        <option value="repair">Women</option>
      </select>
    </div>

    <%= render "shared/search" %>

  </div>
</div>

<br>

<%= render "shared/lender_thumbnail" %>

app/views/borrowers/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h3>Welcome To Keevahh: Sign Up as a Borrower</h3>
</div>
<div class="modal-body">
<%= bootstrap_form_for(:user, url: borrowers_path) do |f| %>
  <%= f.text_field :name %>
  <%= f.email_field :email %>
  <%= f.password_field :password, label: "Password", help: "Must be at least 8 characters long" %>
  <%= f.password_field :password_confirmation, label: "Confirm Password" %>
<div class="modal-footer">
  <%= f.submit "Create Account" %>
  </div>
<% end %>
</div>

app/views/borrowers/_new_loan_request.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h3>Create a new Loan Request</h3>
</div>
<div class="modal-body">
  <%= bootstrap_form_for(:loan_request, url: loan_requests_path) do |f| %>
    <%= f.text_field :title %>
    <%= f.text_area :description %>
    <%= f.text_field :image_url %>
    <%= f.date_field :requested_by_date %>
    <%= f.date_field :repayment_begin_date %>
    <%= f.select :repayment_rate, [["Monthly", "monthly"], ["Weekly", "weekly"]], {}, { class: "selectpicker" } %>
    <%= f.select :category, [["Agriculture", "agriculture"], ["Community", "community"], ["Education", "education"]], { prompt: "Select category" }, { class: "selectpicker" } %>
    <%= f.text_field :amount, prepend: "$", append: ".00" %>
  <div class="modal-footer">
    <%= f.submit "Submit" %>
  </div>
<% end %>
</div>

app/views/borrowers/show.html.erb
<div class="page-header">
  <h1><%= @borrower.name %>'s Projects</h1>
</div>

<% if this_borrower? %>
  <%= render "borrower_show" %>
<% else %>
  <%= render "lender_show" %>
<% end %>