config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get "/browse", to: "loan_requests#index"

  get "/portfolio", to: "borrower_portfolio#show"

  resources :payment, only: [:update]

  resources :loan_requests

  get "/cart", to: "cart#index"
  post "/cart", to: "cart#create"
  delete "/cart", to: "cart#delete"
  put "/cart", to: "cart#update"

  resources :orders, only: [:create, :index, :show, :update]

  get "/login", to: "sessions#new", :as => "login"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  delete "/logout", to: "sessions#destroy"

  resources :lenders

  resources :borrowers

  resources :users, only: [:show]

  get "*path", to: "home#not_found"
end

app/views/shared/_borrower_thumbnail.html.erb
<div class="container">
  <div class="row">
    <% @loan_requests.each do |loan_request| %>
      <div class="col-sm-6 col-md-4 col-lg-4">
      <div class="thumbnail">
        <img src=<%=loan_request.image_url %>  alt="...">
        <div class="caption">
          <div class="thumbnail-label">
            <h3><%= truncate(loan_request.title, length: 20) %></h3>
          </div>
          <p><%= truncate(loan_request.description, length: 30) %></p>
          <p>
            <%= link_to "Details", loan_request_path(loan_request), class: "btn btn-default" %>
            <%= link_to "Edit", edit_loan_request_path(loan_request), remote: true, class: "btn btn-info pull-right" %>
          </p>
          <br>
            <div class="progress">
              <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:<%="#{loan_request.progress_percentage}"%>%;">
                <%="#{loan_request.progress_percentage}%"%>
              </div>
            </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/shared/_lender_thumbnail.html.erb
<div class="container">
  <div class="row">
    <% @loan_requests.each do |loan_request| %>
      <div class="col-sm-6 col-md-4 col-lg-4 loan-request">
      <div class="thumbnail">
        <img src=<%=loan_request.image_url %>  alt="...">
        <div class="caption">
          <div class="thumbnail-label">
            <h3><%= truncate(loan_request.title, length: 20) %></h3>
          </div>
          <p><%= truncate(loan_request.description, length: 30) %></p>
          <p>
            <%= link_to "About", loan_request_path(loan_request), class: "btn btn-default lr-about" %>
            <%= link_to "Contribute $25", cart_path(loan_request: loan_request.id.to_i, amount: 25), method: 'post', class: "btn btn-info pull-right" %>
          </p>
          <br>
            <div class="progress">
              <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:<%="#{loan_request.progress_percentage}"%>%;">
                <%="#{loan_request.progress_percentage}%"%>
              </div>
            </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

<div class="">
  <%= will_paginate @loan_requests %>
</div>

app/views/shared/_search.html.erb
<% cache do %>
<div class="col-md-9">
  <div id="custom-search-input">
    <div class="input-group col-md-4 pull-right">
      <input type="text" class="form-control input-sm" placeholder="Search" />
      <span class="input-group-btn">
        <button class="btn btn-info btn-sm" type="button">
          <i class="fa fa-search"></i>
        </button>
      </span>
    </div>
  </div>
</div>
<% end %>