config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get "/browse", to: "loan_requests#index"

  get "/portfolio", to: "borrower_portfolio#show"

  resources :payment, only: [:update]

  resources :loan_requests

  get "/cart", to: "cart#index"
  post "/cart", to: "cart#create"
  delete "/cart", to: "cart#delete"
  put "/cart", to: "cart#update"

  resources :orders, only: [:create, :index, :show, :update]

  get "/login", to: "sessions#new", :as => "login"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  delete "/logout", to: "sessions#destroy"

  resources :lenders

  resources :borrowers

  resources :users, only: [:show]

  get "*path", to: "home#not_found"
end

app/controllers/borrower_portfolio_controller.rb
class BorrowerPortfolioController < ApplicationController
  def show
    @borrower = current_user
    @loan_requests = @borrower.loan_requests.projects_with_contributions
  end
end

app/views/borrower_portfolio/show.html.erb
<div class="panel panel-success">
  <!-- Default panel contents -->
  <div class="panel-heading"><h1><%= @borrower.name %>'s Portfolio</h1></div>
  <div class="panel-body">
    <h2>Total Funding Received</h2>
    <h4><pre><%= number_to_currency(@borrower.total_contributions_received) %></pre></h4>
    <h3>Total Funding Repayed</h3>
    <h4><pre><%= number_to_currency(@borrower.purse.abs) %></pre></h4>
  </div>
  <% if @loan_requests.empty? %>
    <h2>You have no open projects with contributions</h2>
<% else %>
    <table class="table table-bordered">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th class="text-center">Last Contribution</th>
            <th class="text-center">Title</th>
            <th class="text-center">Amount Donated</th>
            <th class="text-center">Repayment Begin Date</th>
            <th class="text-center">Repayment Rate</th>
            <th class="text-center">Repayment Due Date</th>
            <th class="text-center">Make a Payment</th>
          </tr>
        </thead>
        <tbody>
        <% @loan_requests.each do |loan_request| %>
          <tr>
          <td class="text-center"><%= loan_request.updated_formatted %></td>
          <td class="text-center"><%= loan_request.title %></td>
          <td class="text-center"><%= number_to_currency(loan_request.contributed) %></td>
          <td class="text-center"><%= loan_request.repayment_begin %></td>
          <td class="text-center"><%= loan_request.repayment_rate.capitalize %></td>
          <td class="text-center"><%= loan_request.repayment_due_date %></td>
          <div class="row">
            <td class="text-center">
              <%= form_tag payment_path(loan_request), method: :put do %>
                <%= hidden_field_tag :borrower_id, @borrower.id %>
              <div class="col-xs-6">
                <%= number_field_tag :payment, loan_request.minimum_payment, in: loan_request.minimum_payment..loan_request.contributed, step: 10 %>
              </div>
              <div class="col-xs-3">
                <%= submit_tag "Submit", class: "btn-small btn-info" %>
              </div>
            <% end %>
            </td>
          </div>
        </tr>
      <% end %>
        </tbody>
      </table>
    </div>
  </table>
<% end %>
</div>