config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get "/browse", to: "loan_requests#index"

  get "/portfolio", to: "borrower_portfolio#show"

  resources :payment, only: [:update]

  resources :loan_requests

  get "/cart", to: "cart#index"
  post "/cart", to: "cart#create"
  delete "/cart", to: "cart#delete"
  put "/cart", to: "cart#update"

  resources :orders, only: [:create, :index, :show, :update]

  get "/login", to: "sessions#new", :as => "login"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  delete "/logout", to: "sessions#destroy"

  resources :lenders

  resources :borrowers

  resources :users, only: [:show]

  get "*path", to: "home#not_found"
end

app/views/layouts/_navbar.html.erb
<% cache do %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Keevahh", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_borrower? %>
          <li><%= link_to "Portfolio", portfolio_path %></li>
        <% else %>
        <li><%= link_to "Lend", browse_path %></li>
        <% if !@current_cart.cart_items.empty? %>
        <li role="presentation"><a href="/cart">Basket <span class="badge"><%= @current_cart.cart_items.count %></span></a></li>
        <% else %>
            <li role="presentation" data-toggle="tooltip" data-placement="bottom" title="You don't have any bookings yet."><a href="/cart">Basket <span class="badge">0</span></a></li>
        <% end %>
      <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if current_user && current_user.lender? %>
           <li role="active"><%= link_to "Portfolio", lender_path(current_user) %></li>
          <% end %>
        <% if current_user %>
          <li role="active"><%= link_to "Log out", logout_path, method: :delete, id: "logout" %></li>
        <% else %>
          <li class="active"><a href="#" data-toggle="modal" data-target="#loginModal"> Login <span class="sr-only">(current)</span></a></li>
        <% end %>
       </li>
        <% unless current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" id="sign-up-dropdown" data-toggle="dropdown" role="button" aria-expanded="false">Sign Up<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li role="active"><a href="#" id="sign-up-as-lender" data-toggle="modal" data-target="#lenderSignUpModal"> Sign Up As Lender </a></li>
              <li role="active"><a href="#" id="sign-up-as-borrower" data-toggle="modal" data-target="#borrowerSignUpModal"> Sign Up As Borrower </a></li>
            </ul>
        <% end %>
          </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= render "sessions/new" %>
    </div>
  </div>
</div>

<!-- Lender Signup Modal -->
<div class="modal fade" id="lenderSignUpModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= render "lenders/new" %>
    </div>
  </div>
</div>

<!-- Borrower Signup Modal -->
<div class="modal fade" id="borrowerSignUpModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= render "borrowers/new" %>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Keevahh</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>


    <div class="flash">
      <%= flash_messages %>
    </div>

    <%= yield %>

  </body>

</html>